
name: Build Android APK

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Tools
        run: |
          pip install flet
          pip install -r requirements.txt

      - name: Build APK
        run: flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WorldSafe-App
          path: build/apk/*.apk
